plugins {
    id 'application'
    id 'com.gradleup.shadow' version '9.0.0-beta6'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation libs.junit.jupiter

    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    implementation libs.guava

    implementation libs.dotenv.java
    implementation libs.jackson
    implementation libs.bcrypt
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    mainClass = 'com.greatxlabs.ikaros.server.Servidor'
}

tasks.named('test') {
    useJUnitPlatform()
}

tasks.named('jar') {
    archiveBaseName = 'ikaros-server'
    archiveVersion = '1.1-sin-estado-mision'
    manifest {
        attributes['Main-Class'] = 'com.greatxlabs.ikaros.server.Servidor'
    }
}

tasks.named('shadowJar') {
    archiveBaseName = 'ikaros-server'
    archiveVersion = '1.1-sin-estado-mision'
    archiveClassifier = 'all'
}